apiVersion: v1
kind: Service

metadata:
  name: blue-green-service
  labels:
    app: blue-green-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http-port
      protocol: TCP
  selector:
    # app: blue
    app: green
