apiVersion: apps/v1
kind: Deployment

metadata:
  name: blue-deployment
  labels:
    app: blue-green-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue

  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue-container
          image: nileshgule/blue-green-demo:blue
          resources:
            requests:
              cpu: "10m" #1% of a core
              memory: "150Mi"
            limits:
              cpu: "50m" #5% of a core
              memory: "400Mi"
          imagePullPolicy: Always
      restartPolicy: Always
      
      
