apiVersion: v1
kind: Service

metadata:
  name: canary-service
  labels:
    app: canary-demo
spec:
  type: LoadBalancer
  # type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http-port
      protocol: TCP
  selector:
    app: canary-demo
